title: PizzaByU
email: iconiqdreamscapes@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
"PizzaByU is a customizable pizza ordering web app that lets you build your perfect pizza online.
  Choose from a variety of fresh ingredients, crusts, and sauces, and get your pizza delivered fast.
  Perfect for pizza lovers, parties, and family nights. Order now for a delicious, personalized pizza experience!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hligon35.github.io/pizzabyu/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  hligon35

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
